version: "3.8"

services: 
  db:
    container_name: postgres_db
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
  
  
  core_api: 
    build: .
    container_name: "core-api-container"
    command: bash -c "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/backend
    depends_on:
      - db
    restart: always